language: node_js

node_js:
    - '8.9.4'

cache: npm

jobs:
    include:
        - stage: Installation
          script: npm install
        - stage: Lint
          script: npm run lint
        - stage: Unit tests
          script: npm run test
        - stage: End to end tests
          script: npm run test:e2e
