language: node_js

node_js:
    - '8.9.4'

cache:
    directories:
        - $HOME/.npm

jobs:
    include:
        - stage: Installation
          before_script: cd backend-job-offers
          script: npm install
        - stage: Unit tests
          before_script: cd backend-job-offers
          script: npm run test
        - stage: End to end tests
          before_script: cd backend-job-offers
          script: npm run test:e2e
