language: node_js

node_js:
    - '8.9.4'

services:
    - mysql

cache: npm

before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS job_offers;'

jobs:
    include:
        - stage: Installation
          script: npm install
        - stage: Lint
          script: npm run lint
        - stage: Unit tests
          script: npm run test
        - stage: End to end tests
          script: npm run test:e2e
