language: node_js
node_js:
    - '8.9.4'

jobs:
    include:
        - stage: Installation
          script: npm install
        - stage: Unit tests
          script: npm run test
        - stage: End to end tests
          script: npm run test:e2e
